---
kind: Template
apiVersion: v1
metadata:
  name: pamm-skeleton
  creationTimestamp:
  annotations:
    description: PAMM Digital Application Template v0.1
    iconClass: icon-play
    tags: play,scala
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${WEB_UI_SERVICE_NAME}"
    creationTimestamp:
  spec:
    ports:
    - name: web-ui
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 0
    selector:
      name: "${WEB_UI_SERVICE_NAME}"
    portalIP: ''
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${WEB_UI_SERVICE_NAME}"
    creationTimestamp:
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${WEB_UI_SERVICE_NAME}"
    template:
      metadata:
        creationTimestamp:
        labels:
          name: "${WEB_UI_SERVICE_NAME}"
      spec:
        containers:
        - name: web-ui
          image: pamm-skeleton
          ports:
          - containerPort: 9000
            protocol: TCP
          env:
          - name: MONGODB_URI
            value: mongodb://admin:pamm@localhost:27017/
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 3
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - echo
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 9000
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          capabilities: {}
          securityContext:
            capabilities: {}
            privileged: false
        - name: mongo
          image: openshift/mongodb-24-centos7
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
          - name: MONGODB_USER
            value: pamm
          - name: MONGODB_PASSWORD
            value: pamm
          - name: MONGODB_DATABASE
            value: pamm
          - name: MONGODB_ADMIN_PASSWORD
            value: pamm
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 3
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - echo
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 27017
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          capabilities: {}
          securityContext:
            capabilities: {}
            privileged: false
        restartPolicy: Always
        dnsPolicy: ClusterFirst
  status: {}
parameters:
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  value: openshift
- name: WEB_UI_SERVICE_NAME
  displayName: Web UI Service Name
  description: The name of the OpenShift Service exposed for the web UI.
  value: web-ui
  required: true
labels:
  template: pamm-template
